### ISSUE TITLE
Error Handling in TranslatorAPI.java

### ISSUE THREAD

**Issue by fabianwindbacher** [WoN-Hackathon-2019/translatebot#1]
The errors are only handled with a try/catch block but there is little to no information output.

Example:
1) responseDTO.message = "error with external api";
Maybe state the used api or print the stacktrace
2)
responseDTO.message = "request is in invalid format";
Maybe add an explanation on what format would be valid / print the stacktrace

**Comment by rafiv** [comment]
Thank you for the input, this will immediately be worked on.

**Comment by rafiv** [comment]
resolved
